---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-5.10
- name: centos-6.5
- name: ubuntu-10.04
  run_list: ["recipe[apt]"]
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.6
  run_list: ["recipe[apt]"]

suites:
- name: default
  run_list: ["recipe[zookeeper_bridge_test]"]
  attributes: 
    zookeeper:
      version: 3.4.6
      mirror: http://mirrors.ibiblio.org/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
